version: "3.9"
services:
  npm-registry:
    container_name: "verdaccio"
    image: verdaccio/verdaccio:4
    ports: 
        - 4873:4873
    volumes:
      - ./data/storage:/verdaccio/storage
      - ./data/plugins:/verdaccio/plugins